### PR TITLE
Fix common type replacement logic

### LINKED ISSUE #5100: [openapi-to-tsp]: Common Type Replacement
Currently, the common type reference from M4 will be inlined and replaced by the definition itself. This means conversion tool don't have knowledge whether the model is a user defined model or a model from common type.

Expectation: if the model is user defined, we should convert to a normal model; if the model is from common type, we should convert to some reference to arm library.

### PR DESCRIPTION
**Pull request by pshao25**
Fix #5100

A known issue after this is: if user refers to a common type, we will use the common type in TypeSpec lib, however, if this common type has inner type, I cannot tell whether it is from common type, therefore I'll still generate it.

### CODE REVIEW

File: packages/extensions/openapi-to-typespec/src/autorest-session.ts [hunk 1]
```diff
@@ -5,6 +5,8 @@ let _session: Session<CodeModel>;
 let _armCommonTypeVersion: ArmCommonTypeVersion | undefined;
 let _userSetArmCommonTypeVersion: string;
 
+const commonTypeModels: string[] = [];
```
Comment (live1206) [inline packages/extensions/openapi-to-typespec/src/autorest-session.ts:8]: can we use Set<string>?

File: packages/extensions/openapi-to-typespec/src/autorest-session.ts [hunk 2]
```diff
@@ -14,7 +16,21 @@ export function getSession(): Session<CodeModel> {
 }
 
 export function setArmCommonTypeVersion(version: string): void {
-  _userSetArmCommonTypeVersion = version;
+  if (_userSetArmCommonTypeVersion === undefined) {
+    _userSetArmCommonTypeVersion = version;
+  }
+}
+
+export function setArmCommonTypeModel(model: string): void {
```
Comment (live1206) [inline packages/extensions/openapi-to-typespec/src/autorest-session.ts:24]:
```suggestion
export function addArmCommonTypeModel(model: string): void {
```

File: packages/extensions/openapi-to-typespec/src/autorest-session.ts [hunk 3]
```diff
@@ -14,7 +16,21 @@ export function getSession(): Session<CodeModel> {
...
+  if (!commonTypeModels.includes(model)) {
```
Comment (live1206) [inline packages/extensions/openapi-to-typespec/src/autorest-session.ts:25]: if we use Set<string>, no need to check includes

File: packages/extensions/openapi-to-typespec/src/utils/model-generation.ts [hunk 4]
```diff
@@ -72,3 +82,64 @@ export function generateTemplateModel(templateModel: TypespecTemplateModel): str
 export function generateAdditionalProperties(properties: TypespecObjectProperty[]): string {
   return properties.map((p) => getModelPropertyDeclarations(p).join("\n")).join(";");
 }
+
+const commonTypeMapping: Record<string, string> = {
+  Resource: "Azure.ResourceManager.CommonTypes.Resource",
```
Comment (live1206) [inline packages/extensions/openapi-to-typespec/src/utils/model-generation.ts:87]: consider to remove the namespace if they are always the same

Comment (pshao25) [reply packages/extensions/openapi-to-typespec/src/utils/model-generation.ts:87]: I want to keep this in case they have different namespace.
