### PR TITLE
Fix crash with duplicate paths

### LINKED ISSUE #4882: Fatal error in lintdiff execution resulting in a healthy automated check when it is expected to fail
**Before filling a bug**

- [ X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [ X] have you checked existing issues

In the following run, there was a fatal error encountered. the expectation in such cases is that the fatal error translate into an error for the automated check. However, in this case it resulted in the automated swagger lintdiff check being marked as healthy

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3491008&view=logs&j=0574a2a6-2d0a-5ec6-40e4-4c6e2f70bea2&t=80c3e782-49f0-5d1c-70dd-cbee57bdd0c7

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues
- Autorest command used
```

**Expected behavior**
The automated check for swagger lintdiff should have failed.

**Additional context**

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #4882 too

### CODE REVIEW

File: packages/extensions/core/src/app.ts [hunk 1]
```diff
@@ -351,7 +351,9 @@ async function main() {
     // - doing the inversion (instanceof Error) doesn't reliably work since that seems to return false on Errors marshalled from safeEval
     if (e instanceof Exception) {
       logger.log({ level: "error", message: e.message });
-      exitCode = e.exitCode;
+      if (e.exitCode) {
```
Comment (mikeharder) [inline packages/extensions/core/src/app.ts:354]: Can you explain why this check is needed?  Might be obvious but I don't see it.
