### PR TITLE
Fix: Cannot read property 'pass-thru' of undefined crash

### LINKED ISSUE #3908: [Python]Error when loading AutoRest core (3.0.6373)
Error happened when using 'python -m packaging_tools.generate_sdk -v -m /_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md'. 
I notice it is ok when loading @autorest_core@3.0.6370. What should I do to pin the version to a stable version?
```
===================detailed info========================
root@auto:/_/azure-sdk-for-python# python -m packaging_tools.generate_sdk -v -m /_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md
INFO:__main__:Readme files: ['/_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md']
INFO:packaging_tools.swaggertosdk.autorest_tools:Looking for swagger-to-sdk section in /_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest]AutoRest code generation utility [cli version: 3.0.6339; node: v10.15.0, max-memory: 1280 MB]
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest](C) 2018 Microsoft Corporation.
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest]https://aka.ms/autorest
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest](node:820) ExperimentalWarning: The fs.promises API is experimental
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest]   Loading AutoRest core      '/root/.autorest/@autorest_core@3.0.6373/node_modules/@autorest/core/dist' (3.0.6373)
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest](node:831) ExperimentalWarning: The fs.promises API is experimental
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest]  TypeError: Cannot read property 'pass-thru' of undefined
[Autorest] https://aka.ms/autorest
[Autorest] (node:820) ExperimentalWarning: The fs.promises API is experimental
[Autorest]    Loading AutoRest core      '/root/.autorest/@autorest_core@3.0.6373/node_modules/@autorest/core/dist' (3.0.6373)
[Autorest] (node:831) ExperimentalWarning: The fs.promises API is experimental
[Autorest]   TypeError: Cannot read property 'pass-thru' of undefined
ERROR:packaging_tools.swaggertosdk.autorest_tools:Command '['/usr/local/bin/autorest', '/_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md', '--perform-load=false', '--swagger-to-sdk', '--output-artifact=configuration.json', '--input-file=foo', '--output-folder=/tmp/tmpk_wler0m']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_sdk.py", line 137, in <module>
    generate_main()
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_sdk.py", line 134, in generate_main
    args.force)
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_sdk.py", line 42, in generate
    extract_conf_from_readmes(swagger_files_in_pr, restapi_git_folder, repotag, config, force_generation=force_generation)
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py", line 195, in extract_conf_from_readmes
    build_swaggertosdk_conf_from_json_readme(readme_file, sdk_git_id, config, base_folder=restapi_git_folder, force_generation=force_generation)
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py", line 225, in build_swaggertosdk_conf_from_json_readme
    temp_dir
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py", line 27, in autorest_swagger_to_sdk_conf
    execute_simple_command(cmd_line.split())
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py", line 148, in execute_simple_command
    output
subprocess.CalledProcessError: Command '['/usr/local/bin/autorest', '/_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md', '--perform-load=false', '--swagger-to-sdk', '--output-artifact=configuration.json', '--input-file=foo', '--output-folder=/tmp/tmpk_wler0m']' returned non-zero exit status 1.
```

### PR DESCRIPTION
**Pull request by kant2002**
Validate that value is available before reading configuration.

Offending plugin in my case with `imodeler1`
Fixes #3908

### CODE REVIEW

File: packages/extensions/core/src/lib/pipeline/pipeline.ts [hunk 1]
```diff
@@ -359,11 +359,12 @@ export async function runPipeline(configView: AutorestContext, fileSystem: IFile
 
     // you can have --pass-thru:FOO on the command line
     // or add pass-thru: true in a pipline configuration step.
+    const configEntry = context.GetEntry(node.configScope.last.toString());
     const passthru =
-      context.GetEntry(node.configScope.last.toString())["pass-thru"] === true ||
+      (configEntry && configEntry["pass-thru"] === true) ||
```
Comment (timotheeguerin) [inline packages/extensions/core/src/lib/pipeline/pipeline.ts:364]:
```suggestion
      configEntry?.["pass-thru"] === true ||
```

you can use the `safe navigation operator` here instead.

File: packages/extensions/core/src/lib/pipeline/pipeline.ts [hunk 2]
```diff
@@ -359,11 +359,12 @@ export async function runPipeline(configView: AutorestContext, fileSystem: IFile
...
       values(configView.GetEntry("pass-thru")).any((each) => each === pluginName);
     const usenull =
-      context.GetEntry(node.configScope.last.toString())["null"] === true ||
+      (configEntry && configEntry["null"] === true) ||
```
Comment (timotheeguerin) [inline packages/extensions/core/src/lib/pipeline/pipeline.ts:367]:
```suggestion
      configEntry?.["null"] === true ||
```

File: common/changes/@autorest/core/patch-1_2021-03-14-18-45.json [hunk 3]
```diff
@@ -0,0 +1,11 @@
+{
+  "changes": [
+    {
+      "packageName": "@autorest/core",
+      "comment": "",
+      "type": "none"
```
Comment (timotheeguerin) [inline common/changes/@autorest/core/patch-1_2021-03-14-18-45.json:6]:
```suggestion
      "type": "patch"
```

File: common/changes/@autorest/core/patch-1_2021-03-14-18-45.json [hunk 4]
```diff
@@ -0,0 +1,11 @@
+{
+  "changes": [
+    {
+      "packageName": "@autorest/core",
+      "comment": "",
```
Comment (timotheeguerin) [inline common/changes/@autorest/core/patch-1_2021-03-14-18-45.json:5]:
```suggestion
      "comment": "**Fix** Cannot read property 'pass-thru' of undefined crash",
```

**Comment by timotheeguerin** [comment]
@kant2002 thanks for this fix!

File: common/changes/@autorest/core/patch-1_2021-03-14-18-45.json (hunk 3 above)
Comment (kant2002) [reply common/changes/@autorest/core/patch-1_2021-03-14-18-45.json:6]: Interesting type of workflow. Thanks for helping me with that.

**Comment by kant2002** [comment]
@timotheeguerin I waiting long time until this project start has reasonable response time for contributions :)

File: common/changes/@autorest/core/patch-1_2021-03-14-18-45.json (hunk 3 above)
Comment (timotheeguerin) [reply common/changes/@autorest/core/patch-1_2021-03-14-18-45.json]: yeah its using rush monorepo tool which use those change files to genrate teh changelogs when releasing

**Review by timotheeguerin — APPROVED** [review]

File: packages/extensions/core/src/lib/pipeline/pipeline.ts [hunk 5]
```diff
@@ -359,11 +359,12 @@ export async function runPipeline(configView: AutorestContext, fileSystem: IFile
...
     // you can have --pass-thru:FOO on the command line
     // or add pass-thru: true in a pipline configuration step.
+    const configEntry = context.GetEntry(node.configScope.last.toString());
     const passthru =
-      context.GetEntry(node.configScope.last.toString())["pass-thru"] === true ||
+      configEntry?.["pass-thru"] === true ||
       values(configView.GetEntry("pass-thru")).any((each) => each === pluginName);
     const usenull =
-      context.GetEntry(node.configScope.last.toString())["null"] === true ||
+      configEntry?.["null"] === true ||
```
Comment (timotheeguerin) [inline packages/extensions/core/src/lib/pipeline/pipeline.ts:367]: I think you'll just want to reformat this file again after my last suggestion, to pass the ci.
