### PR TITLE
Literate Documentation Update

### LINKED ISSUE #1900: Operator '??' cannot be applied to operands of type 'Guid' and 'string'
When generating C# against an API that takes an array of guid on the query string, autorest outputs code that fails to compile

```C#
foreach (var _item in ids)
{
    _queryParameters.Add(string.Format("ids={0}", System.Uri.EscapeDataString(_item ?? string.Empty)));
}
```

**_item ?? string.Empty**  causes 

> CS0019 Operator '??' cannot be applied to operands of type 'Guid' and 'string'

Seems to be the same root issue as #1648 

The below swagger causes a repro on 1.0.0-Nightly20170212

``` javascript
{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "title"
    },
    "host": "localhost",
    "schemes": ["http"],
    "paths": {
        "/test": {
            "delete": {
                "tags": ["test"],
                "operationId": "deleteTest",
                "consumes": [],
                "produces": [],
                "parameters": [{
                    "name": "ids",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uuid",
                        "x-nullable": false
                    },
                    "collectionFormat": "multi",
                    "x-nullable": true
                }],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
    },
    "definitions": {

    }
}
```

### PR DESCRIPTION
**Pull request by olydis**
...and
- fixed a race condition (cached a bit too much when converting ASTs to objects)
- fixed #1900 (again, cough)
- made jsonpath library do filters right

### CODE REVIEW

File: Samples/3a-literate-swagger/Client/Models/ListQueryKeysResult.cs [hunk 1]
```diff
@@ -29,8 +26,9 @@ public ListQueryKeysResult()
         /// <summary>
         /// Initializes a new instance of the ListQueryKeysResult class.
         /// </summary>
-        /// <param name="value">The query keys for the Azure Search
-        /// service.</param>
+        /// <param name="value">&gt; Again, shorthand for `@.properties.value`
+        ///
```
Comment (fearthecowboy) [inline Samples/3a-literate-swagger/Client/Models/ListQueryKeysResult.cs]: What's with the `&gt;` ? I've seen a couple of these.

File: Samples/3a-literate-swagger/Client/Models/ListQueryKeysResult.cs [hunk 2]
```diff
@@ -43,7 +41,9 @@ public ListQueryKeysResult(IList<QueryKey> value = default(IList<QueryKey>))
         partial void CustomInit();
 
         /// <summary>
-        /// Gets the query keys for the Azure Search service.
+        /// Gets &amp;gt; Again, shorthand for `@.properties.value`
```
Comment (fearthecowboy) [inline Samples/3a-literate-swagger/Client/Models/ListQueryKeysResult.cs]: And now `&amp;gt;` ? Inception!

File: Samples/3a-literate-swagger/generated/swagger.md.json [hunk 3]
```diff
@@ -49,7 +48,8 @@
             "$ref": "#/parameters/ResourceGroupName"
           },
           {
-            "$ref": "#/parameters/SearchServiceName"
+            "$ref": "#/parameters/SearchServiceName",
+            "description": "> Search is also performed relative to nodes discovered by parent headings.\n>\n> In this case, we're in the scope of the node identified by `#QueryKeys_List` which is the operation.\n>\n> Furthermore, `#SearchServiceName` is really shorthand for `@.#SearchServiceName` where `@` represents the current scope's node.\n> One could force searching the global scope with `$.#SearchServiceName`\n\nSome description."
```
Comment (fearthecowboy) [inline Samples/3a-literate-swagger/generated/swagger.md.json]: `>` ? Should that be stripped by the GFM stripper?

Comment (olydis) [inline Samples/3a-literate-swagger/generated/swagger.md.json]: that one runs on the code model (it was simpler that way) :/ we may indeed wanna change that since other endpoints may benefit from stripping GFM (but not force that, otherwise our "swagger resolver" endpoint may do unexpected magic to some people)

File: Samples/3a-literate-swagger/Client/Models/ListQueryKeysResult.cs (hunk 1 above)
Comment (olydis) [inline Samples/3a-literate-swagger/Client/Models/ListQueryKeysResult.cs]: darn, fixed!
