### PR TITLE
Fixes #881 - failure to accept x-* vendor extension in path

### LINKED ISSUE #881: vendor extensions within path
Haven't tested if validation fails for other fields, but at least for the paths field the extension "x-vendor-testy" causes validation to fail:

``` json
{
  "swagger": "2.0",
  "info": {
    "version": "2.0",
    "title": "My web service",
    "description": "No description provided.",
    "x-endpoint-name": "default"
  },
  "host": "dsw12.net:999",
  "basePath": "/sandbox/8c88389038102937482abf83f8f/services/5b737fefc19b3047ab4f3234cd34642df2",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/swagger.json": {
        "get": {
            "summary": "Get swagger API document for the web service",
            "operationId": "getSwaggerDocument",
            "parameters": [
                {
                    "name": "api-version",
                    "in": "query",
                    "description": "API version",
                    "required": false,
                    "type": "string",
                    "default": "2.0",
                    "enum": [
                        "2.0"
                    ]
                }
            ],
            "responses": {
                "200": {
                    "description": "Swagger API document for this service"
                }
            }
        }
    },
    "x-vendor-testy" :  "asd"
  }
}
```

I get Error parsing swagger file. Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path 'paths.x-vendor-testy', line 45, position 29.

According to http://swagger.io/specification/#pathsObject and I spoke with some people on the swagger IRC channel, this is valid swagger:

npm install -g swagger-tools && swagger-tools validate "http://pastebin.com/raw/8LWmz7zp" --verbose

I guess this means if vendors do specify extensions to the schema, they can't use autoRest - I think you should ignore them

### PR DESCRIPTION
**Pull request by fearthecowboy**
Simple fix for #881 to not fail when a vendor extension is used in a path.

### CODE REVIEW

File: AutoRest/Modelers/Swagger/JsonConverters/PathItemRefConverter.cs [hunk 1]
```diff
@@ -25,6 +25,13 @@ public override bool CanConvert(System.Type objectType)
         public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue,
             JsonSerializer serializer)
         {
+            // is the leaf an vendor extension? "x-*..."
+            if (reader == null || reader.Path.Substring(reader.Path.LastIndexOf(".", StringComparison.Ordinal) + 1).StartsWith("x-",StringComparison.CurrentCulture))
+            {
+                // skip x-* vendor extensions when used where the path would be.
+                return new Dictionary < string, Operation >();
```
Comment (tbombach) [inline AutoRest/Modelers/Swagger/JsonConverters/PathItemRefConverter.cs]: Minor: spacing? I think these spaces will be removed the next time someone formats the document

**Comment by tbombach** [comment]
LGTM
